/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Dir_scan {
	char *filename;
	int dimfile;
};
typedef struct Dir_scan Dir_scan;

struct Res {
	int first;
	int second;
	int third;
};
typedef struct Res Res;

#define FILEPROG 0x20000013
#define FILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTAFILE 1
extern  Res * contafile_1(char **, CLIENT *);
extern  Res * contafile_1_svc(char **, struct svc_req *);
#define CONTADIR 2
extern  int * contadir_1(Dir_scan *, CLIENT *);
extern  int * contadir_1_svc(Dir_scan *, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTAFILE 1
extern  Res * contafile_1();
extern  Res * contafile_1_svc();
#define CONTADIR 2
extern  int * contadir_1();
extern  int * contadir_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Dir_scan (XDR *, Dir_scan*);
extern  bool_t xdr_Res (XDR *, Res*);

#else /* K&R C */
extern bool_t xdr_Dir_scan ();
extern bool_t xdr_Res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
