/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_Dir_scan (XDR *xdrs, Dir_scan *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dimfile))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Res (XDR *xdrs, Res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->first))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->second))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->third))
		 return FALSE;
	return TRUE;
}
