/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "esercitazione9.h"

bool_t
xdr_registro (XDR *xdrs, registro *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidato, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->giudice, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->categoria, 2))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomeFile, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fase, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_giudice (XDR *xdrs, giudice *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giudici, 256,
		sizeof (giudice), (xdrproc_t) xdr_giudice))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_esprimi_voto (XDR *xdrs, input_esprimi_voto *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidato, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->op, 2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_voidInput (XDR *xdrs, voidInput *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_voidOutput (XDR *xdrs, voidOutput *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}
