/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fattore.h"

bool_t
xdr_giudice (XDR *xdrs, giudice *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giudici, 256,
		sizeof (giudice), (xdrproc_t) xdr_giudice))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_esprimi_voto (XDR *xdrs, input_esprimi_voto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->candidato, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->op, 2,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
